In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
# one -hot encoding

In [6]:
X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4,nb_classes]),name='weight')
b = tf.Variable(tf.random_normal([nb_classes]),name='bias')

In [7]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step % 200 ==0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 9.2413435
200 0.7027065
400 0.5808537
600 0.4847318
800 0.39339548
1000 0.3031822
1200 0.23873565
1400 0.21637341
1600 0.19772318
1800 0.18190843
2000 0.16834004
--------------
[[1.925326e-02 9.807370e-01 9.836072e-06]] [1]
--------------
[[0.7523439  0.22949624 0.0181599 ]] [0]
--------------
[[2.5406234e-08 4.3434306e-04 9.9956566e-01]] [2]
--------------
[[1.9253293e-02 9.8073685e-01 9.8360806e-06]
 [7.5234407e-01 2.2949606e-01 1.8159889e-02]
 [2.5406235e-08 4.3434306e-04 9.9956566e-01]] [1 0 2]
