In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


In [3]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [5]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y* tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [6]:
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [7]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.73203 [[ 0.7288166   0.71536213 -1.1801533 ]
 [-0.5775373  -0.1298833   1.6072978 ]
 [ 0.48373488 -0.51433605 -2.02127   ]]
1 3.317995 [[ 0.6621908   0.7479632  -1.1461285 ]
 [-0.81948906  0.03000022  1.689366  ]
 [ 0.23214607 -0.33772916 -1.9462881 ]]
2 2.0218027 [[ 0.6434202   0.74127686 -1.1206716 ]
 [-0.8116129  -0.00900118  1.7204912 ]
 [ 0.20866647 -0.3507957  -1.909742  ]]
3 1.9710885 [[ 0.6235321   0.7400824  -1.099589  ]
 [-0.80967706 -0.01636278  1.725917  ]
 [ 0.17870611 -0.3366575  -1.8939198 ]]
4 1.9446771 [[ 0.60733104  0.7366499  -1.0799555 ]
 [-0.79007834 -0.03363192  1.7235874 ]
 [ 0.16691464 -0.3340635  -1.8847224 ]]
5 1.9235673 [[ 0.59031737  0.7351024  -1.0613943 ]
 [-0.77496755 -0.04048848  1.7153332 ]
 [ 0.15076596 -0.322094   -1.8805432 ]]
6 1.9035922 [[ 0.57437915  0.7326286  -1.0429822 ]
 [-0.75527763 -0.05151999  1.7066748 ]
 [ 0.13977787 -0.31497923 -1.8766699 ]]
7 1.88408 [[ 0.5581266   0.7307179  -1.024819  ]
 [-0.7377567  -0.05928205  1.696916  ]
 [ 0.

# non-normalized

In [8]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  2519695600000.0 
Prediction:
 [[1120640. ]
 [2254801.8]
 [1774008. ]
 [1243902. ]
 [1465807.9]
 [1478132.2]
 [1354844.2]
 [1724677.4]]
1 Cost:  2.7683404e+27 
Prediction:
 [[-3.7114280e+13]
 [-7.4714848e+13]
 [-5.8775478e+13]
 [-4.1201298e+13]
 [-4.8557931e+13]
 [-4.8966637e+13]
 [-4.4879615e+13]
 [-5.7140673e+13]]
2 Cost:  inf 
Prediction:
 [[1.2302029e+21]
 [2.4765244e+21]
 [1.9481925e+21]
 [1.3656725e+21]
 [1.6095181e+21]
 [1.6230651e+21]
 [1.4875953e+21]
 [1.8940044e+21]]
3 Cost:  inf 
Prediction:
 [[-4.0776728e+28]
 [-8.2087735e+28]
 [-6.4575462e+28]
 [-4.5267056e+28]
 [-5.3349646e+28]
 [-5.3798677e+28]
 [-4.9308349e+28]
 [-6.2779334e+28]]
4 Cost:  inf 
Prediction:
 [[1.3515997e+36]
 [2.7209087e+36]
 [2.1404409e+36]
 [1.5004377e+36]
 [1.7683460e+36]
 [1.7832298e+36]
 [1.6343917e+36]
 [2.0809057e+36]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]

In [9]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

'''
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
'''

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  6.008363 
Prediction:
 [[-2.787303  ]
 [-2.3049731 ]
 [-1.9524162 ]
 [-1.5445647 ]
 [-1.8520749 ]
 [-1.818827  ]
 [-1.0787338 ]
 [-0.97747326]]
1 Cost:  6.0079103 
Prediction:
 [[-2.7871776 ]
 [-2.304853  ]
 [-1.9523162 ]
 [-1.5444872 ]
 [-1.8519831 ]
 [-1.8187385 ]
 [-1.078675  ]
 [-0.97741604]]
2 Cost:  6.007457 
Prediction:
 [[-2.7870522]
 [-2.3047333]
 [-1.9522161]
 [-1.5444096]
 [-1.851891 ]
 [-1.8186496]
 [-1.0786163]
 [-0.9773588]]
3 Cost:  6.007004 
Prediction:
 [[-2.786927 ]
 [-2.304613 ]
 [-1.9521161]
 [-1.5443