In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

#x가 많을 수록 더 정확하게 예측 할 수 있다.

In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]),name='weight1')
w2 = tf.Variable(tf.random_normal([1]),name='weight2')
w3 = tf.Variable(tf.random_normal([1]),name='weight3')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [6]:
hypothesis = x1 * w1 + x2*w2 + x3*w3 + b

In [7]:
cost = tf.reduce_mean(tf.square(hypothesis -Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ =sess.run([cost, hypothesis, train],
                                  feed_dict ={x1:x1_data, x2:x2_data,x3:x3_data,Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  62547.29 
Prediction:
 [-75.96345  -78.27629  -83.83015  -90.80436  -56.976482]
10 Cost:  14.468626 
Prediction:
 [145.26407 187.59541 178.152   194.48586 145.81136]
20 Cost:  13.822504 
Prediction:
 [145.9478  188.39003 178.94907 195.3521  146.41212]
30 Cost:  13.749193 
Prediction:
 [145.96422 188.38263 178.95592 195.35777 146.4012 ]
40 Cost:  13.67629 
Prediction:
 [145.97856 188.3728  178.96031 195.36082 146.38844]
50 Cost:  13.603815 
Prediction:
 [145.99286 188.36302 178.9647  195.36386 146.37572]
60 Cost:  13.531695 
Prediction:
 [146.00711 188.35324 178.9691  195.3669  146.36302]
70 Cost:  13.459941 
Prediction:
 [146.02135 188.34352 178.9735  195.36995 146.35036]
80 Cost:  13.388664 
Prediction:
 [146.03552 188.33382 178.97784 195.37292 146.33774]
90 Cost:  13.317709 
Prediction:
 [146.04967 188.32413 178.98221 195.37595 146.32515]
100 Cost:  13.247167 
Prediction:
 [146.06377 188.31447 178.98654 195.37894 146.31259]
110 Cost:  13.176931 
Prediction:
 [146.07785 188.3

# Matrix로 대체한다.

In [10]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [11]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [12]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [13]:
hypothesis = tf.matmul(X,W)+b

In [15]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))
#reduce_mean은 특정 차원을 제거하고 평균을 구한다. 

In [16]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  126121.6 
Prediction:
 [[-159.22546]
 [-197.2163 ]
 [-191.33363]
 [-208.02669]
 [-152.1618 ]]
10 Cost:  13.88883 
Prediction:
 [[154.90442]
 [180.36963]
 [180.69513]
 [197.10442]
 [135.84653]]
20 Cost:  12.66907 
Prediction:
 [[155.84157]
 [181.52121]
 [181.81673]
 [198.32695]
 [136.73022]]
30 Cost:  12.604097 
Prediction:
 [[155.83116]
 [181.53383]
 [181.81612]
 [198.3274 ]
 [136.74516]]
40 Cost:  12.539477 
Prediction:
 [[155.81792]
 [181.54295]
 [181.8121 ]
 [198.32414]
 [136.75745]]
50 Cost:  12.47522 
Prediction:
 [[155.8047 ]
 [181.55206]
 [181.8081 ]
 [198.3209 ]
 [136.76968]]
60 Cost:  12.411319 
Prediction:
 [[155.79152]
 [181.56114]
 [181.80411]
 [198.31767]
 [136.78188]]
70 Cost:  12.347745 
Prediction:
 [[155.77838]
 [181.57019]
 [181.80013]
 [198.31444]
 [136.79405]]
80 Cost:  12.284572 
Prediction:
 [[155.76527]
 [181.5792 ]
 [181.79616]
 [198.31122]
 [136.80618]]
90 Cost:  12.221657 
Prediction:
 [[155.7522]
 [181.5882]
 [181.7922]
 [198.308 ]
 [136.8183]]
100 C

In [ ]:
# matrix 원하는 데로 쉽게 구현할 수 있다.