In [3]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [4]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

# X and Y data
x_train = [1, 2, 3]
y_train = [1, 2, 3]

In [5]:
W = tf.Variable(tf.random_normal([1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")
# 값이 하나인

In [6]:
hypothesis = x_train * W + b

In [7]:
cost = tf.reduce_mean(tf.square(hypothesis-y_train))

In [8]:
t = [1.,2.,3.,4.]
tf.reduce_mean(t) # 평균

<tf.Tensor 'Mean_1:0' shape=() dtype=float32>

In [9]:
optimizer= tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b))

0 2.8232925 [2.1286771] [-0.8523567]
20 0.19035071 [1.533928] [-1.0505961]
40 0.15135698 [1.4572546] [-1.0239124]
60 0.1372696 [1.4308538] [-0.9779527]
80 0.124668695 [1.4101374] [-0.93219817]
100 0.113226034 [1.3908179] [-0.8884077]
120 0.102833636 [1.3724468] [-0.8466577]
140 0.093395196 [1.3549428] [-0.80686814]
160 0.084823035 [1.3382617] [-0.7689483]
180 0.07703763 [1.3223647] [-0.7328106]
200 0.06996683 [1.3072149] [-0.69837123]
220 0.06354501 [1.2927768] [-0.66555053]
240 0.05771263 [1.2790174] [-0.6342722]
260 0.05241553 [1.2659047] [-0.6044637]
280 0.04760463 [1.2534082] [-0.57605624]
300 0.043235283 [1.2414987] [-0.5489837]
320 0.039266955 [1.2301493] [-0.52318335]
340 0.035662856 [1.2193329] [-0.49859563]
360 0.03238958 [1.2090253] [-0.47516343]
380 0.029416746 [1.1992017] [-0.45283243]
400 0.026716756 [1.18984] [-0.43155095]
420 0.02426458 [1.1809182] [-0.4112697]
440 0.022037484 [1.1724157] [-0.39194155]
460 0.020014798 [1.164313] [-0.3735217]
480 0.01817775 [1.1565907] [-

In [15]:
X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, W_val, b_val,_= sess.run([cost, W, b, train],
                    feed_dict={X: [1, 2, 3], y: [1, 2, 3]})
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)

0 3.5240757 [2.1286771] [-0.8523567]
20 0.19749945 [1.533928] [-1.0505961]
40 0.15214379 [1.4572546] [-1.0239124]
60 0.13793248 [1.4308538] [-0.9779527]
80 0.12527026 [1.4101374] [-0.93219817]
100 0.11377231 [1.3908179] [-0.8884077]
120 0.10332986 [1.3724468] [-0.8466577]
140 0.09384582 [1.3549428] [-0.80686814]
160 0.08523231 [1.3382617] [-0.7689483]
180 0.077409334 [1.3223647] [-0.7328106]
200 0.07030442 [1.3072149] [-0.69837123]
220 0.06385163 [1.2927768] [-0.66555053]
240 0.05799109 [1.2790174] [-0.6342722]
260 0.052668452 [1.2659047] [-0.6044637]
280 0.047834326 [1.2534082] [-0.57605624]
300 0.04344389 [1.2414987] [-0.5489837]
320 0.03945643 [1.2301493] [-0.52318335]
340 0.035834953 [1.2193329] [-0.49859563]
360 0.032545887 [1.2090253] [-0.47516343]
380 0.029558683 [1.1992017] [-0.45283243]
400 0.026845647 [1.18984] [-0.43155095]
420 0.024381677 [1.1809182] [-0.4112697]
440 0.022143835 [1.1724157] [-0.39194155]
460 0.020111376 [1.164313] [-0.3735217]
480 0.01826544 [1.1565907] [-0

In [16]:
X = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, W_val, b_val,_= sess.run([cost, W, b, train],
                    feed_dict={X: [1, 2, 3,4,5], 
                               y: [2.1, 3.1, 4.1,5.1,6.1]})
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)

0 3.5240757 [2.1286771] [-0.8523567]
20 0.19749945 [1.533928] [-1.0505961]
40 0.15214379 [1.4572546] [-1.0239124]
60 0.13793248 [1.4308538] [-0.9779527]
80 0.12527026 [1.4101374] [-0.93219817]
100 0.11377231 [1.3908179] [-0.8884077]
120 0.10332986 [1.3724468] [-0.8466577]
140 0.09384582 [1.3549428] [-0.80686814]
160 0.08523231 [1.3382617] [-0.7689483]
180 0.077409334 [1.3223647] [-0.7328106]
200 0.07030442 [1.3072149] [-0.69837123]
220 0.06385163 [1.2927768] [-0.66555053]
240 0.05799109 [1.2790174] [-0.6342722]
260 0.052668452 [1.2659047] [-0.6044637]
280 0.047834326 [1.2534082] [-0.57605624]
300 0.04344389 [1.2414987] [-0.5489837]
320 0.03945643 [1.2301493] [-0.52318335]
340 0.035834953 [1.2193329] [-0.49859563]
360 0.032545887 [1.2090253] [-0.47516343]
380 0.029558683 [1.1992017] [-0.45283243]
400 0.026845647 [1.18984] [-0.43155095]
420 0.024381677 [1.1809182] [-0.4112697]
440 0.022143835 [1.1724157] [-0.39194155]
460 0.020111376 [1.164313] [-0.3735217]
480 0.01826544 [1.1565907] [-0

In [17]:
print(sess.run(hypothesis, feed_dict={X: [5]}))
print(sess.run(hypothesis, feed_dict={X: [2.5]}))
print(sess.run(hypothesis, feed_dict={X: [1.5, 3.5]}))

[0.9948611 1.9988972 3.0029333]
[0.9948611 1.9988972 3.0029333]
[0.9948611 1.9988972 3.0029333]
